export const products = [
    {
      id: 1,
      name: "Men's Streetwear Fashion Style Big Pocket Cotton Long Sleeve Shirt Blue / XL",
      category: "Baju",
      price: 30,
      image: "/images/products/baju-1.png",
      isCart: false,
      description: "This shirt features a vibrant and eye-catching color and a solid pattern that will give you a happy feeling. Its long sleeve design makes it an ideal choice for men. The turn-down collar adds to comfort and stylish look. Its versatile design and great fit make it an ideal choice for casual occasions. Specifications Style: Casual Sleeve Style: Regular Sleeve Length(cm): Full Shirts Type: Casual Shirts Pattern Type: Solid Origin: CN(Origin) Model Number: C6112 Material: Cotton Item T",
    },
    {
      id: 2,
      name: "Casual Long Sleeve Plaid Shirt - jiu hong / XXL(65-70KG)",
      category: "Sepatu",
      price: 20,
      image: "/images/products/sepatu-2.png",
      isCart: false,
      description: "Regular fit Denim design Classic collar Long buttoned sleeve Patch pocket on the chest Button up The model is 187 cm tall and is wearing a size M",
    },
    {
      id: 3,
      name: "Men's Streetwear Fashion Style Big Pocket Cotton Long Sleeve Shirt Gray / XL",
      category: "Baju",
      price: 17,
      image: "/images/products/baju-3.png",
      isCart: false,
      description: "Navy Blue Preppy Long Sleeve Polyester Plaid Shirt Non-Stretch Spring/Fall Men Tops",
    },
    {
      id: 4,
      name: "Sinopsis cerita",
      category: "Cerita",
      image: "",
      isCart: false,
      description: "Majo no Tabitabi: The Journey of Elaina sendiri berkisah mengenai seorang gadis bernama Elaina yang sejak kecil terpesona dengan kisah-kisah yang ditulis dalam buku favoritnya, terutama tentang Nike yakni seorang penyihir terkenal yang memiliki banyak perjalanan hebat di seluruh dunia. Elaina pun menjadi ingin mengalami petualangan yang mengaggumkan sendiri, ia berusaha menjadi seorang penyihir. Meskipun banyak cobaan yang menghadangnya ia yakin akhirnya akan berhasil",
    },
    {
      id: 5,
      name: "Batch Freelancer Men's Button Down Shirt in Aluminum Gray",
      category: "Baju",
      price: 10,
      image: "/images/products/baju-5.png",
      isCart: false,
      description: "White Casual Short Sleeve Cotton Plain Top Embellished Non-Stretch Summer Men Tops",
    }
  ];